# NumPy

This course introduces NumPy for scientific computing.

# Part 2: Indexing and Slicing

In this part you learn how to access and manipulate parts of an `ndarray`, mainly by indexing and slicing.


### Indexing

Single elements can be accessed by standart Python sequence indexing syntax: `x[i]`. 

In [2]:
import numpy as np


x = np.arange(9)
print(x)

# get the first element
print(x[0])

# get the second last element
print(x[-2])

[0 1 2 3 4 5 6 7 8]
0
7


Multidimensional indexing works similar with either `x[i][j]`, `x[i, j]` or `x[(i, j)]`.

In [3]:
# convert to two dimensional array with shape (3, 3)
x.shape = (3, 3)
print(x)

# get element at (1, 1)
print(x[1][1])  # dont use this, performance is suboptimal
print(x[1, 1])
print(x[(1, 1)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4
4
4


### Slicing and striding

The Python slicing concept is as well extended to N dimensions. A slicing notation is `start:stop:step`.

In [4]:
x = np.arange(12)
print(x)

# get a slice from index 2 to 4 (exlusive)
print(x[2:4])

# get last three elements
print(x[-3:])

# get every second element (stride = 2)
print(x[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[2 3]
[ 9 10 11]
[ 0  2  4  6  8 10]


This works as well on multidimensional arrays.

In [5]:
# convert to two dimensional array with shape (3, 4)
x.shape = (3, 4)
print(x)

# get a slice (2, 2)
print(x[:2, :2])

# get third row
print(x[2, :])
print(x[2])  # equivalent with single index

# get first column
print(x[:, 0])  # shape (3,)
print(x[:, 0:1])  # shape (3, 1)

# stride of two
print(x[::2, ::2])  # shape (2, 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]]
[ 8  9 10 11]
[ 8  9 10 11]
[0 4 8]
[[0]
 [4]
 [8]]
[[ 0  2]
 [ 8 10]]


### Note on copies and views!

Slicing operations return a `view` to an array. A view has its own metadata but shares the undelying data buffer containing the element values. To make a copy use `x.copy()`. Some examples:

In [ ]:
x = np.arange(6).reshape(2, 3)
print(x)
print(x.base is not None)

# view on the first two columns
x_view = x[:, :2]
print(x_view)

# mutate view (mutates x as well)
x_view[0, 0] = 9
print(x)

# reshape creates a view or a copy, yolo!
x_reshaped = x.reshape(3, 2)
x_reshaped[1, -1] = 99
print(x)

# test if array is a view
print(x_reshaped.base is not None)

# make a copy to duplicate the buffer
x_copy = x[:, :2].copy()
# mutate copy (no changes to x or x_view)
x_copy[0, 0] = 0
print(x_copy)
print(x)

# asigning an array to another variable just creates a pointer to the same object
x_another = x  # share data and metadata
x_another.shape = (3, 2)
print(x.shape)

### Advanced Indexing

Indexing is also possible with integer or boolean lists or ndarrays.

In [ ]:
x = np.arange(10)

# select multiple by index
print(x[[4, 9, 0]])

# filter
f = x > 5
print(f)
print(x[f])

### Assignment with Indexing

Partial assignment works together with indexing.

In [6]:
# set values lager than five to 99
x[x > 5] = 99
print(x)

# asign values from another array of same shape as the indexed view
x[::2] = np.zeros(5)
print(x)

[[ 0  1  2  3]
 [ 4  5 99 99]
 [99 99 99 99]]


ValueError: could not broadcast input array from shape (5,) into shape (2,4)

### Broadcasting

Many operations on ndarrays, like for example matrix multiplication, require a matching combination of shapes to work and make sense. In NumPy broadcasting ist the process of stretching arrays to match up automatically whenever possible.

In [9]:
import numpy as np


x = np.zeros(9).reshape(3, 3)

# add one: somewhat expected to perform elements wise

print("first",x+1)
# add array: broadcast along the first axis
print(x + np.arange(3))

# add matrix with one row to matrix with one column
row = np.arange(3).reshape(1, -1)
column = np.arange(4).reshape(-1, 1)
print(row * column)  # shape (3,4)

first [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[0 0 0]
 [0 1 2]
 [0 2 4]
 [0 3 6]]
