# NumPy

This course introduces NumPy for scientific computing.

## Part 1: Basics

This part covers the following basic concepts of NumPy:

- The `ndarray` data model
- Array Creation Routines
- Array Manipulation Routines
- Linear Algebra Routines

### Introduction

NumPy (**Num**erical **Py**thon) is an open source Python library that’s widely used in science and engineering[^1]. For example, you can use it for working with vectors, matrices, linear algebra, optimization and much more. Behind the scene it relies on C++ libraries for numeric calculations. It is comparably fast as it is designed around Python's buffer interface which means that for many operations that one can do, no data is being copied.


### The `ndarray` data model

The central data structure in NumPy is the `ndarray` object. It encapsulates n-dimensional arrays of homogeneous types. Classical computers have a linear main memory. That is, somehow, we can have memory space for one or more variables of the same type, say N numbers, but we cannot (initially) have a memory for a 3x3 matrix. The nD-array data structure is now a wrapper which *internally* reserves spaces for a certain number of values, but is associated with shape and stride information telling, how this 1D array of values is going to be interpreted as a n-dimensional array. Some aspects (e.g., strides) are not visible from Python, so we will ignore them for now, but the shape is an important concept.



### Creation and Inspection

Lets create some arrays and inspect their values and shape.

In [4]:
import numpy as np

# create and array from a list (or tuple)
A = np.array([1, 2, 3, 4])
print("array:", A)

# print shape
print("shape:", A.shape)

# print the number of dimensions and number of elements
print("ndim (number of dimensions):", A.ndim)
print("size (number of elements):", A.size)

A = np.transpose(A)
print(A)

array: [1 2 3 4]
shape: (4,)
ndim (number of dimensions): 1
size (number of elements): 4
[1 2 3 4]


Some more common ways to create and array. For a full list of possible array creation routines see <https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation>

In [5]:
# integer range
A = np.arange(4)
print("range:\n", A)
print("shape:", A.shape)

# zeros
A = np.zeros(3)
print("zeros:\n", A)
print("shape:", A.shape)

# ones
A = np.ones(3)
print("ones:\n", A)
print("shape:", A.shape)

# random floats
A = np.random.rand(2, 3)
print("random (float):\n", A)
print("shape:", A.shape)

# eye
A = np.eye(2)
print("eye:\n", A)
print("shape:", A.shape)

range:
 [0 1 2 3]
shape: (4,)
zeros:
 [0. 0. 0.]
shape: (3,)
ones:
 [1. 1. 1.]
shape: (3,)
random (float):
 [[0.94801134 0.99501777 0.66145441]
 [0.16599463 0.00666771 0.14558471]]
shape: (2, 3)
eye:
 [[1. 0.]
 [0. 1.]]
shape: (2, 2)


### Array Manipulations

With the `reshape` function one can change the shape of an array. The size will stay the same, hence the dimensions must match.

Considering an array with 4 values and the shape is a tuple with a single entry 4. Let us turn this into a 2x2 matrix:

In [6]:
# array with 4 values and shape (4,)
A = np.array([1, 2, 3, 4])
print("array:\n", A)
print("shape", A.shape)

# reshape to a 2x2 matrix
m = A.reshape(2, 2)
print("matrix:\n", m)
print("shape", m.shape)



array:
 [1 2 3 4]
shape (4,)
matrix:
 [[1 2]
 [3 4]]
shape (2, 2)


One can use `-1` to indicate an automatically determined a fitting shape value for one dimension.

In [ ]:
# create array with 4 values and shape (4,)
A = np.array([1, 1, 1, 1])
print(A)
print("shape", A.shape)

# reshape to shape (x, 1)
B = A.reshape(-1, 1)
print(B)
print("shape", B.shape)

There are many more built in routines, like for example, stacking, transpose, joining, splitting and tiling, to manipulate an array. For a complete list, see <https://numpy.org/doc/stable/reference/routines.array-manipulation.html>

In [10]:
# stack
A = np.array([1, 1])
B = np.array([2, 2])

S = np.stack((A, B), axis=1)
print("stack:\n", S)

H = np.hstack((A, B))
print("hstac:\n", H)

V = np.vstack((A, B))
print("vstac:\n", V)

# transpose
m = np.arange(4).reshape(2, 2)
print("matrix:\n", m)
m_transposed = m.transpose()  # same as m.T
print("transpose:\n", m_transposed)

stack:
 [[1 2]
 [1 2]]
hstac:
 [1 1 2 2]
vstac:
 [[1 1]
 [2 2]]
matrix:
 [[0 1]
 [2 3]]
transpose:
 [[0 2]
 [1 3]]


### Linear Algebra - Matrix Multiplication

Matrix multiplication is now easy. And many other linear algebra things, see <https://numpy.org/doc/stable/reference/routines.linalg.html>

In [8]:
x1 = np.array([1, 1])
x2 = np.array([2, 2])

# matrix multiplication
y = np.matmul(x1, x2)  # same as `x1 @ x2`
print(y)

y = x1 @ x2 

print(y)
# dot product
#y2 = np.dot(x1, x2)
#print(y2)

4
4
